version: 2

sources:
  - name: stitch_facebook_ads
    tables:
      - name: s_adcreative
        identifier: adcreative
        loaded_at_field: _sdc_batched_at
      - name: s_ads
        identifier: ads
        loaded_at_field: _sdc_batched_at
      - name: s_adsets
        identifier: adsets
        loaded_at_field: _sdc_batched_at
      - name: s_campaigns
        identifier: campaigns
        loaded_at_field: _sdc_batched_at
      - name: s_ads_insights_age_and_gender
        identifier: ads_insights_age_and_gender
        loaded_at_field: _sdc_batched_at
