version:  2

sources:
  - name: fivetran_hubspot_crm
    database: ra-development
    schema: fivetran_hubspot_euwest2
    tables:
      - name: s_company
        identifier: company
        loaded_at_field: _fivetran_synced
      - name: s_contact
        identifier: contact
        loaded_at_field: _fivetran_synced
      - name: s_deal_pipeline
        identifier: deal_pipeline
        loaded_at_field: _fivetran_synced
      - name: s_deal_pipeline_stages
        identifier: deal_pipeline_stage
        loaded_at_field: _fivetran_synced
      - name: s_deal
        identifier: deal
        loaded_at_field: _fivetran_synced
      - name: s_engagement
        identifier: engagement
        loaded_at_field: _fivetran_synced
      - name: s_owner
        identifier: owner
        loaded_at_field: _fivetran_synced
      - name: s_deal_company
        identifier: deal_company
        loaded_at_field: _fivetran_synced
      - name: s_property_history
        identifier: deal_property_history
        loaded_at_field: _fivetran_synced
  - name: stitch_hubspot_crm
    database: ra-development
    schema: stitch_hubspot
    tables:
      - name: s_companies
        identifier: companies
        loaded_at_field: _sdc_batched_at
      - name: s_contacts
        identifier: contacts
        loaded_at_field: _sdc_batched_at
      - name: s_deal_pipelines
        identifier: deal_pipelines
        loaded_at_field: _sdc_batched_at
      - name: s_deals
        identifier: deals
        loaded_at_field: _sdc_batched_at
      - name: s_engagements
        identifier: engagements
        loaded_at_field: _sdc_batched_at
      - name: s_owners
        identifier: owners
        loaded_at_field: _sdc_batched_at
models:
  - name: stg_hubspot_crm_contacts
    description: "Hubspot Contacts Dimension Staging"
    columns:
      - name: contact_id
        tests:
          - unique
          - not_null
      - name: contact_created_date
        tests:
          - not_null
  - name: stg_hubspot_crm_companies
    columns:
      - name: hubspot_company_id
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
  - name: stg_hubspot_crm_deals
    columns:
      - name: hubspot_company_id
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
      - name: deal_stage_label
        tests:
          - not_null
      - name: deal_delivery_start_ts
        tests:
          - not_null
      - name: hubspot_company_name
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
      - name: deal_delivery_schedule_ts
        tests:
          - not_null
      - name: hubspot_company_name
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
      - name: deal_number_of_sprints
        tests:
          - not_null
  - name: stg_hubspot_crm_pipelines
    columns:
      - name: pipelineid
        description: This is a unique identifier for the pipe line
        tests:
          - unique
          - not_null
  - name: stg_hubspot_crm_pipeline_stages
    columns:
      - name: stageid
        description: This is a unique identifier for the pipe line
        tests:
          - unique
          - not_null
  - name: stg_hubspot_crm_owners
    columns:
      - name: ownerid
        description: HubSpot uses owners to assign CRM objects (contacts, companies, and deals) to specific people in your organization.
