version: 2

sources:
  - name: hubspot_crm
    database: ra-development
    schema: stitch_hubspot
    tables:
      - name: companies
      - name: contacts
      - name: deal_pipelines
      - name: deals
      - name: engagements
      - name: owners

models:
  - name: sde_hubspot_crm_contacts_ds
    description: "Hubspot Contacts Dimension Staging"
    columns:
      - name: contact_id
        tests:
          - unique
          - not_null
      - name: contact_created_date
        tests:
          - not_null
  - name: sde_hubspot_crm_companies
    columns:
      - name: hubspot_company_id
        description: This is a unique identifier for the customer within HubSpot
        tests:
          - not_null
          - unique
  - name: sde_hubspot_crm_pipelines
    columns:
      - name: pipelineid
        description: This is a unique identifier for the pipe line
        tests:
          - unique
          - not_null
  - name: sde_hubspot_crm_pipeline_stages
    columns:
      - name: stageid
        description: This is a unique identifier for the pipe line
        tests:
          - unique
          - not_null
  - name: sde_hubspot_crm_owners
    columns:
      - name: ownerid
        description: HubSpot uses owners to assign CRM objects (contacts, companies, and deals) to specific people in your organization.
