version: 2

sources:
  - name: stitch_intercom
    database: ra-development
    schema: stitch_intercom
    tables:
      - name: s_contacts
        identifier: contacts
        loaded_at_field: _sdc_batched_at
      - name: s_conversations
        identifier: conversations
        loaded_at_field: _sdc_batched_at
