version:  2

models:
  - name: stg_stripe_subscriptions_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_alternative_id
        tests:
          - unique
          - not_null
      - name: customer_source
        tests:
          - not_null
  - name: stg_stripe_subscriptions_subscriptions
    columns:
      - name: subscription_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
            - relationships:
              to: ref('stg_stripe_subscriptions_customers')
              field: customer_id
      - name: plan_id
        tests:
            - relationships:
              to: ref('stg_stripe_subscriptions_plans')
              field: plan_id
  - name: stg_stripe_subscriptions_plans
    columns:
      - name: plan_id
        tests:
          - unique
          - not_null
      - name: plan_name
        tests:
          - not_null
      - name: plan_interval
        tests:
          - not_null
