
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ra_bi_apps'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ra_bi_apps'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
on-run-start:
    - "create table if not exists {{ target.schema }}_meta.audit_dbt_results (object string, status string, row_count numeric, execution_time numeric, error_message string, load_ts timestamp)"
on-run-end:
    - "insert into {{ target.schema }}_meta.audit_dbt_results (object, status, row_count, execution_time, error_message, load_ts) values {{ results_values(results) }}"

models:
  ra_bi_apps:
      sde_adapters:
          materialized: view
          schema: staging
      sil_marts:
          materialized: table

  vars:
      enable_harvest_projects_source:      true
      enable_hubspot_crm_source:           true
      enable_asana_projects_source:        true
      enable_jira_projects_source:         true
      enable_stripe_payments_source:       true
      enable_xero_accounting_source:       true
      enable_mailchimp_email_source:       true
      enable_segment_events_source:        true
      enable_crm_warehouse:         true
      enable_finance_warehouse:     true
      enable_projects_warehouse:    true
      enable_marketing_warehouse:   true
seeds:
  ra_bi_apps:
    schema: seed_data
