version: 2

sources:
  - name: looker_usage
    database: ra-development
    schema: fivetran_email
    tables:
      - name: s_usage_stats
        identifier: usage_stats
        loaded_at_field: _fivetran_synced
