version: 2

sources:

- name: harvest_projects
  database: ra-development
  schema: rittman_analytics
  tables:
    - name: s_clients
      identifier: clients
      loaded_at_field: _sdc_batched_at
    - name: s_contacts
      identifier: contacts
      loaded_at_field: _sdc_batched_at
    - name: s_estimate_item_categories
      identifier: estimate_item_categories
      loaded_at_field: _sdc_batched_at
    - name: s_expense_categories
      identifier: expense_categories
      loaded_at_field: _sdc_batched_at
    - name: s_expenses
      identifier: expenses
      loaded_at_field: _sdc_batched_at
    - name: s_invoice_item_categories
      identifier: invoice_item_categories
      loaded_at_field: _sdc_batched_at
    - name: s_invoice_line_items
      identifier: invoice_line_items
      loaded_at_field: _sdc_batched_at
    - name: s_invoice_payments
      identifier: invoice_payments
      loaded_at_field: _sdc_batched_at
    - name: s_invoices
      identifier: invoices
      loaded_at_field: _sdc_batched_at
    - name: s_project_tasks
      identifier: project_tasks
      loaded_at_field: _sdc_batched_at
    - name: s_project_users
      identifier: project_users
      loaded_at_field: _sdc_batched_at
    - name: s_projects
      identifier: projects
      loaded_at_field: _sdc_batched_at
    - name: s_roles
      identifier: roles
      loaded_at_field: _sdc_batched_at
    - name: s_tasks
      identifier: tasks
      loaded_at_field: _sdc_batched_at
    - name: s_time_entries
      identifier: time_entries
      loaded_at_field: _sdc_batched_at
    - name: s_user_project_tasks
      identifier: user_project_tasks
      loaded_at_field: _sdc_batched_at
    - name: s_user_projects
      identifier: user_projects
      loaded_at_field: _sdc_batched_at
    - name: s_user_roles
      identifier: user_roles
      loaded_at_field: _sdc_batched_at
    - name: s_users
      identifier: users
      loaded_at_field: _sdc_batched_at

models:
  - name: stg_harvest_projects_contacts
    columns:
        - name: id
          description: "Unique identifier of a Harvest invoice entry, primary key"
          tests:
              - unique
              - not_null
  - name: stg_harvest_projects_timesheets
    columns:
        - name: id
          description: "Unique identifier of a Harvest time entry, primary key"
          tests:
              - unique
              - not_null
