version: 2
models:
  - name: sil_timesheet_projects_dim
    description: "Timesheet Projects Dimension"
    columns:
      - name: timesheet_project_pk
        tests:
          - unique
          - not_null
  - name: sil_delivery_projects_dim
    description: "Delivery Projects Dimension"
    columns:
      - name: delivery_project_pk
        tests:
          - unique
          - not_null
  - name: sil_users_dim
    description: "Staff Dimension"
    columns:
      - name: user_pk
        tests:
          - unique
          - not_null
  - name: sil_timesheet_tasks_dim
    description: "Projects Dimension"
    columns:
      - name: timesheet_task_pk
        tests:
          - unique
          - not_null
  - name: sil_delivery_tasks_dim
    description: "Projects Dimension"
    columns:
      - name: timesheet_task_pk
        tests:
          - unique
          - not_null
  - name: sil_timesheets_fact
    description: "Projects Dimension"
    columns:
      - name: timesheet_pk
        tests:
          - unique
          - not_null
      - name: company_pk
        tests:
          - not_null
          - relationships:
              to: ref('sil_companies_dim')
              field: company_pk
      - name: user_pk
        tests:
          - not_null
          - relationships:
              to: ref('sil_users_dim')
              field: user_pk
      - name: project_pk
        tests:
          - not_null
          - relationships:
              to: ref('sil_timesheet_projects_dim')
              field: timesheet_project_pk
      - name: timesheet_task_pk
        tests:
          - not_null
          - relationships:
              to: ref('sil_timesheet_tasks_dim')
              field: timesheet_task_pk
