
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ra_data_warehouse'
version: '0.0.1'

# This setting configures which "profile" dbt uses for this project.
profile: 'ra_data_warehouse'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
on-run-start:
    - "create table if not exists {{ generate_prefixed_target_name() }}_logs.audit_dbt_results (object string, status string, row_count numeric, execution_time numeric, load_ts timestamp)"

on-run-end:
    - "insert into {{ generate_prefixed_target_name() }}_logs.audit_dbt_results (object, status, row_count, execution_time, load_ts) values {{ results_values(results) }}"

models:
  ra_data_warehouse:
      adapters:
          materialized: view
          schema: staging
      integration:
          materialized: view
          schema: staging
      warehouse:
          materialized: table
      utils:
          materialized: view
          schema: logs

  vars:
# data sources
      enable_harvest_projects_source:      true
      enable_hubspot_crm_source:           true
      enable_asana_projects_source:        true
      enable_jira_projects_source:         true
      enable_stripe_payments_source:       true
      enable_xero_accounting_source:       true
      enable_mailchimp_email_source:       true
      enable_segment_events_source:        true
      enable_google_ads_source:            true
      enable_facebook_ads_source:          true
      enable_looker_usage_source:          true
      enable_intercom_messaging_source:    true
# warehouse modules
      enable_crm_warehouse:         true
      enable_finance_warehouse:     true
      enable_projects_warehouse:    true
      enable_marketing_warehouse:   true
      enable_ads_warehouse:         true
      enable_product_warehouse:     true

      segment_sessionization_trailing_window: 3
      segment_inactivity_cutoff: 30 * 60

seeds:
  ra_data_warehouse:
    schema: logs
