version: 2

sources:
  - name: stitch_facebook_ads_2
    schema: "{{ var('stg_facebook_ads_2_stitch_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: insights
        identifier: ads_insights
      - name: adsets
      - name: ads
      - name: campaigns
