version: 2
models:
  - name: sil_projects_dim
    description: "Projects Dimension"
    columns:
      - name: project_pk
        tests:
          - unique
          - not_null
  - name: sil_users_dim
    description: "Staff Dimension"
    columns:
      - name: user_pk
        tests:
          - unique
          - not_null
  - name: sil_tasks_dim
    description: "Projects Dimension"
    columns:
      - name: task_pk
        tests:
          - unique
          - not_null
  - name: sil_timesheets_fact
    description: "Projects Dimension"
    columns:
      - name: timesheet_pk
        tests:
          - unique
          - not_null
      - name: company_pk
        tests:
          - not_null
          - relationships:
              to: ref('sil_companies_dim')
              field: company_pk
      - name: user_pk
        tests:
          - not_null
          - relationships:
              to: ref('sil_users_dim')
              field: user_pk
      - name: project_pk
        tests:
          - not_null
          - relationships:
              to: ref('sil_projects_dim')
              field: project_pk
      - name: task_pk
        tests:
          - not_null
          - relationships:
              to: ref('sil_tasks_dim')
              field: task_pk
