version: 2

sources:

  - name: stitch_mailchimp
    database: ra-development
    schema: stitch_mailchimp
    tables:
      - name: campaigns
      - name: list_members
      - name: list_segment_members
      - name: list_segments
      - name: lists
      - name: reports_email_activity
      - name: unsubscribes
